config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  mount Maily::Engine, at: '/maily'
  get 'accounts/new'

  # Action cable
  mount ActionCable.server => '/cable'

  constraints(SubdomainPresent) do
    root 'users#index', as: :subdomain_root

    # users - routes
    devise_for :users, path: ''
    resources :users, path: '', only: :index
    namespace :users, path: '' do
      resources :appointments
      resources :branches
      resources :comments
      resources :profiles do
        member do
          get :roles
          patch :update_roles
        end
      end
      resources :roles do
        member do
          get :permissions
          patch :update_permissions
        end
      end
      resources :settings
      resources :help, only: :index
      resources :customers
      resources :call_logs do
        member do
          post  :create_comment
          patch :transition
        end
      end
      resources :lands
      resources :properties do
        member do
          patch :upload_pic
          get   :remove_pic
          patch :transition
          get   :new_rent
          get   :new_sale
          post  :payment
          patch :download_pics
        end
      end
      resources :geocodes do
        collection do
          get :location
        end
      end
      resources :filters do
        collection do
          get :options
        end
      end
    end
  end  

  constraints(SubdomainBlank) do 
    root 'home#index'
    resources :accounts, only: [:index, :new, :create] do
      collection do
        get :forgot
        post :remember
        post :find_team
      end
    end

    # admins - routes
    resources :admins, only: :index
    devise_for :admins
  end

  # IP blacklisting for admin website
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  resourcify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable, :timeoutable

  belongs_to :branch, optional: true
  has_many :properties
  has_many :call_logs
  has_many :comments
  has_many :payments
  has_one  :account
  has_and_belongs_to_many :roles, :join_table => :users_roles

  # Nested attributes
  accepts_nested_attributes_for :roles

  def name
    "#{first_name} #{last_name}"
  end

  def initials
    "#{first_name[0]}#{last_name[0]}"
  end

  def self.current_user
    Thread.current[:user]
  end

  def self.current_user=(user)
    Thread.current[:user] = user
  end

  def privileges_check(action, field)
    current_privileges[field].try(:[], action) || false
  end

  def can?(action, field)
    privileges_check(action, field)
  end

  def current_privileges
    @privileges ||= build_privileges
  end

  private

  def build_privileges
    temp_hash = {}
    roles.map(&:policy).pluck(:specs).each do |spec| 
      spec.each do |key, values|
        unless temp_hash[key].present?
          temp_hash[key] = {}
        end
        temp_hash[key] = values
      end
    end
    return temp_hash
  end
end

app/controllers/users/appointments_controller.rb
class Users::AppointmentsController < UsersController
  before_action :find_call_log, except: %i[index]
  before_action :find_appointment, except: %i[index new create]

  def index
    respond_to do |format|
      format.html {
        @appointments_grid = initialize_grid(Appointment,
                                          name: 'appointment',
                                          include: [:call_log, :user, :customer],
                                          enable_export_to_csv: true,
                                          order:  'appointments.created_at',
                                          order_direction: 'desc')
        export_grid_if_requested('appointment' => 'appointment_grid')
      }
    end
  end

  def new
    @appointment = @call_log.appointments.new
    @appointment.user_id = current_user.id
    @appointment.customer_id = @call_log.customer_id
  end

  def create
    @appointment = @call_log.appointments.new(appointment_params)
    @appointment.user_id = current_user.id
    @appointment.customer_id = @call_log.customer_id

    if @appointment.save
      flash[:success] = "Appointment successfully created"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @appointment.update_attributes(appointment_params)
      flash[:success] = "Appointment was successfully updated"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @appointment.destroy
      flash[:success] = 'Appointment was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end

    redirect_to users_call_log_path(@call_log)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:scheduled_date, :scheduled_time, :state)
  end

  def find_call_log
    unless params[:cid].present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end

    @call_log = CallLog.find params[:cid]
    unless @call_log.present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end
  end
  
  def find_appointment
    @appointment = @call_log.appointments.find params[:id]
    unless @appointment.present?
      flash[:alert] = "Appointment not found"
      redirect_back fallback_location: users_call_logs_path
    end
  end
end

app/controllers/users/billings_controller.rb
class Users::BillingsController < UsersController
  def index
    respond_to do |format|
      format.html {
        @billing_grid = initialize_grid(Bill,
                                        name: 'bill',
                                        enable_export_to_csv: true)
        export_grid_if_requested('bill' => 'bill_grid')
      }
    end
  end
end

app/controllers/users/branches_controller.rb
module Users
  class BranchesController < UsersController
    before_action :find_branch, only: [:edit, :update, :destroy]

    def index
      @branches = Branch.all
    end

    def new
      @branch = Branch.new
    end

    def create
      @branch = Branch.new(branch_params)
      if @branch.save
        flash[:success] = 'Branch successfully created.'
        redirect_to users_branches_path
      else
        flash[:error] = 'Something went wrong'
        render 'new'
      end
    end

    def edit
    end

    def update
      if @branch.update_attributes(branch_params)
        flash[:success] = 'Branch was successfully updated'
        redirect_to users_branches_path
      else
        flash[:error] = 'Something went wrong'
        render 'edit'
      end
    end

    def destroy
      if @object.destroy
        flash[:success] = 'Branch was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end

      redirect_to users_branches_path
    end


    private

    def branch_params
      params.require(:branch).permit(:name, :code, :telephone, :location)
    end

    def find_branch
      @branch = Branch.find(params[:id])
      unless @branch.present?
        flash[:error] = 'Branch not found.'
        redirect_to users_branches_path
      end
    end
  end
end

app/controllers/users/call_logs_controller.rb
module Users
  class CallLogsController < UsersController
    before_action :find_call_log, except: [:index, :new, :create]

    def index
      respond_to do |format|
        format.html {
          @filterrific = initialize_filterrific(
            record_scope.page(params[:page]),
            params[:filterrific],
            persistence_id: false
          ) || return

          @call_logs_grid = initialize_grid(@filterrific.find.page(params[:page]),
                                            name: 'call_log',
                                            include:  [:customer, :user, :comments],
                                            order:  'call_logs.created_at',
                                            order_direction: 'desc')
          export_grid_if_requested('call_log' => 'call_log_grid')
        }
  
        format.json {
        }
      end
    end

    def new
      @call_log = current_user.call_logs.new
      @call_log.build_customer
    end

    def create
      @log = current_user.call_logs.new(log_params)
      if @log.save
        flash[:success] = "Call Log successfully created."
        redirect_to users_call_log_path(@log)
      else
        flash[:error] = "Something went wrong while creating call log."
        render 'new'
      end
    end

    def edit
    end

    def update
      if @call_log.update_attributes(log_params)
        flash[:success] = "Call Log was successfully updated"
        redirect_to users_call_log_path(@call_log)
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
    end

    def destroy
      if @call_log.destroy
        flash[:success] = 'Call Log was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end

      redirect_to users_call_logs_path
    end

    def transition
      begin
        if @call_log.update_attribute(:state, log_params[:state])
          flash[:success] = "Call Log is now #{@call_log.state.humanize}."
        else
          flash[:error] = "Error changing status"
        end
      rescue => exception
        flash[:error] = "Sorry, you are unallowed to '#{log_params[:state]}' property. "
      end

      redirect_to users_call_log_path(@call_log)
    end

    private

    def log_params
      params.require(:call_log).permit(:budget_currency, :budget_amount, :status,
                                  :property_locations, :property_names,
                                  customer_attributes: [:first_name, :last_name, :telephone])
    end

    def record_scope
      if can?("view_all", "call_logs")
        CallLog.includes(:user).where(deleted_at: nil).order(created_at: :desc)
      else
        current_user.call_logs.includes(:user).where(deleted_at: nil).order(created_at: :desc)
      end
    end

    def find_call_log
      @call_log = record_scope.find(params[:id])
      unless @call_log.present?
        flash[:error] = "Call Log not found"
        redirect_to users_call_logs_path
      end
    end
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < UsersController
  before_action :find_call_log
  before_action :find_comment, except: [:new, :create]

  def new
    @comment = @call_log.comments.new
    @comment.user_id = current_user.id
  end

  def create
    @comment = @call_log.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      @call_log.update_attribute(:status, @comment.state)
      flash[:success] = "Comment successfully created"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(comment_params)
      @call_log.update_attribute(:status, @call_log.comments.last&.state || @call_log.status)
      flash[:success] = "Comment was successfully updated"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @comment.destroy
      @call_log.update_attribute(:status, @call_log.comments.last&.state || "Response pending")
      flash[:success] = 'Comment was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end

    redirect_to users_call_log_path(@call_log)
  end


  private
  def comment_params
    params.require(:comment).permit(:details, :state)
  end

  def find_call_log
    unless params[:cid].present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end

    @call_log = CallLog.find params[:cid]
    unless @call_log.present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end
  end

  def find_comment
    @comment = @call_log.comments.find params[:id]
    unless @comment.present?
      flash[:alert] = "comment not found"
      redirect_back fallback_location: users_call_logs_path
    end
  end
end

app/controllers/users/customers_controller.rb
class Users::CustomersController < UsersController
  def index
    respond_to do |format|
      format.html { 
        @q = Customer.ransack(params[:q])
        @customers = @q.result(distinct: true).page params[:page]
       }

      format.json {
      }
    end
  end
end

app/controllers/users/filters_controller.rb
class Users::FiltersController < UsersController
  # params - type
  # 1. property
  def index
    results = 
      case params[:type]
      when 'property'
        Property.new.as_json.keys.sort
      else
        Property.new.as_json.keys.sort
      end

    render json: results, status: :ok
  end

  def options
    unless params[:field].present?
      render json: [], status: :ok
      return ;
    end

    results = 
      case params[:type]
      when 'property'
        Property.select(:"#{params[:field]}").all.pluck(:"#{params[:field]}").uniq.compact.sort
      end

    render json: results, status: :ok
  end
end

app/controllers/users/geocodes_controller.rb
module Users
  class GeocodesController < UsersController
    def location
      results = Geocoder.search([params[:lat], params[:lng]])
      result = results.first
      address = result.data['address']
      render json: {address: result.address,
                    city: address['city'],
                    state: address['state'],
                    suburb: address['suburb'],
                    road: address['road'],
                    postcode: address['postcode']}, status: :ok
    end
  end
end

app/controllers/users/help_controller.rb
class Users::HelpController < UsersController
end

app/controllers/users/lands_controller.rb
class Users::LandsController < UsersController
  before_action :find_land, only: [:edit, :update, :destroy]

  def index
  end

  def new
  end

  def edit
  end

  def update
    if @land.update_attributes(land_params)
      flash[:success] = "Land details was successfully updated"
      redirect_to users_land_path(@land)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def transition
    begin
      if @land.send("#{land_params[:state]}!")
        flash[:success] = "Land is now #{@land.state}."
      else
        flash[:error] = "Error uploading image."
      end
    rescue => exception
      flash[:error] = "Sorry, you are unallowed to '#{land_params[:state]}' property. "
    else
    end

    redirect_to users_land_path(@land)
  end

  private

  def land_params
    params.require(:land).permit(:amount, :currency, :customer_id, :state)
  end

  def find_land
    @land = record_scope.find(params[:id])
    unless @land.present?
      flash[:error] = "Land details not found"
      redirect_to users_lands_path
    end
  end

  def record_scope
    if can?("view_all", "lands")
      Land.where(deleted_at: nil).order(created_at: :desc)
    else
      current_user.lands.order(created_at: :desc)
    end
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < UsersController
  before_action :find_property

  def index
    @images = @property.images.map(&:service_url)
    render json: {images: @images}, status: :ok
  end

  private
  def find_property
    @property = current_user.properties.find_by_id(params[:property_id])
    unless @property.present?
      render json: {error: 'Property not found'}, status: :failed
      return ;
    end
  end
end

app/controllers/users/settings_controller.rb
module Users
  class SettingsController < UsersController
    def index
    
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  private
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path(subdomain: current_account.subdomain_name)
    end
  end
end

app/helpers/users/appointments_helper.rb
module Users::AppointmentsHelper
end

app/helpers/users/billings_helper.rb
module Users::BillingsHelper
end

app/helpers/users/branches_helper.rb
module Users::BranchesHelper
end

app/views/users/profiles/_form.slim
= simple_form_for(@user, defaults: { wrapper: false }, as: :user, method: action, url: url) do |f|
  .row
    .col-md-4.form-group
      = f.input :first_name, label: "First Name", input_html: {class: 'form-control'}
    .col-md-4.form-group
      = f.input :last_name, label: "Last Name", input_html: {class: 'form-control'}
    .col-md-4.form-group
      = f.input :email, label: "Email", input_html: {class: 'form-control'}
    .col-md-4.form-group
      = f.input :password, label: "Password", input_html: {class: 'form-control'}
    .col-md-4.form-group
      = f.input :password_confirmation, label: "Confirm Password", input_html: {class: 'form-control'}
  .row
    .col-md-4
      = f.button :submit, class: 'form-control btn-success'

app/views/users/profiles/edit.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 Users
          p.mb-md-0 Edit member's information.
    br
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor Users / &nbsp; 
          p.text-primary.mb-0.hover-cursor Edit

.row
  .col-md-12.stretch-card
    .card
      .card-body
        = render partial: 'form', locals: {url: users_profile_path(@user), action: :patch}

app/views/users/profiles/index.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 Users
          p.mb-md-0 Invite members into your organization.
    br
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-primary.mb-0.hover-cursor Users

.row
  .col-md-12.stretch-card
    .card
      .card-body
        a.btn.btn-primary href="#{new_users_profile_path}"
          i.mdi.mdi-plus
          | &nbsp; Invite Member
        .table-responsive
          table#recent-purchases-listing.table
            thead
              tr
                th First Name
                th Last Name
                th Email
                th Role
                th Branch
                th
            tbody
              - @users.each do |user|
                tr
                  td = user.first_name
                  td = user.last_name
                  td = user.email
                  td
                    = link_to  "Set Role", roles_users_profile_path(user)
                    pre
                      = user.roles.map(&:name).join("\n")
                  td Main branch
                  td width="15%"
                    = link_to('<i class="mdi mdi-pencil btn-icon-prepend"></i> Edit'.html_safe, edit_users_profile_path(user))
                    ' &nbsp; &nbsp;
                    = link_to('<i class="mdi mdi-delete btn-icon-prepend"></i> Delete'.html_safe, users_profile_path(user), method: 'DELETE', data: {confirm: 'Do you want to delete?'})

app/views/users/profiles/new.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 Users
          p.mb-md-0 Invite members into your organization.
    br
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor Users / &nbsp; 
          p.text-primary.mb-0.hover-cursor New

.row
  .col-md-12.stretch-card
    .card
      .card-body
        = render partial: 'form', locals: {url: users_profiles_path, action: :post}

app/views/users/profiles/roles.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 Roles
          p.mb-md-0 Set user role
    br
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor Users / &nbsp; 
          p.text-muted.mb-0.hover-cursor Roles / &nbsp;
          p.text-primary.mb-0.hover-cursor Edit

.row
  .col-md-12.stretch-card
    .card
      .card-body
        = simple_form_for(@user, as: :user, method: :patch, url: users_profile_path(@user)) do |f|
          .row
            .col-md-4.form-group
              = f.select(:role_ids, Role.all.collect{|role| [role.name, role.id]}, {}, { :multiple => true, :size => 5, class: 'form-control'})
          .row
            .col-md-4
              = f.button :submit, 'Update Role', class: 'form-control btn-success'