config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  mount Maily::Engine, at: '/maily'
  get 'accounts/new'

  # Action cable
  mount ActionCable.server => '/cable'

  constraints(SubdomainPresent) do
    root 'users#index', as: :subdomain_root

    # users - routes
    devise_for :users, path: ''
    resources :users, path: '', only: :index
    namespace :users, path: '' do
      resources :appointments
      resources :branches
      resources :comments
      resources :profiles do
        member do
          get :roles
          patch :update_roles
        end
      end
      resources :roles do
        member do
          get :permissions
          patch :update_permissions
        end
      end
      resources :settings
      resources :help, only: :index
      resources :customers
      resources :call_logs do
        member do
          post  :create_comment
          patch :transition
        end
      end
      resources :lands
      resources :properties do
        member do
          patch :upload_pic
          get   :remove_pic
          patch :transition
          get   :new_rent
          get   :new_sale
          post  :payment
          patch :download_pics
        end
      end
      resources :geocodes do
        collection do
          get :location
        end
      end
      resources :filters do
        collection do
          get :options
        end
      end
    end
  end  

  constraints(SubdomainBlank) do 
    root 'home#index'
    resources :accounts, only: [:index, :new, :create] do
      collection do
        get :forgot
        post :remember
        post :find_team
      end
    end

    # admins - routes
    resources :admins, only: :index
    devise_for :admins
  end

  # IP blacklisting for admin website
end

app/controllers/users/appointments_controller.rb
class Users::AppointmentsController < UsersController
  before_action :find_call_log, except: %i[index]
  before_action :find_appointment, except: %i[index new create]

  def index
    respond_to do |format|
      format.html {
        @appointments_grid = initialize_grid(Appointment,
                                          name: 'appointment',
                                          include: [:call_log, :user, :customer],
                                          enable_export_to_csv: true,
                                          order:  'appointments.created_at',
                                          order_direction: 'desc')
        export_grid_if_requested('appointment' => 'appointment_grid')
      }
    end
  end

  def new
    @appointment = @call_log.appointments.new
    @appointment.user_id = current_user.id
    @appointment.customer_id = @call_log.customer_id
  end

  def create
    @appointment = @call_log.appointments.new(appointment_params)
    @appointment.user_id = current_user.id
    @appointment.customer_id = @call_log.customer_id

    if @appointment.save
      flash[:success] = "Appointment successfully created"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @appointment.update_attributes(appointment_params)
      flash[:success] = "Appointment was successfully updated"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @appointment.destroy
      flash[:success] = 'Appointment was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end

    redirect_to users_call_log_path(@call_log)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:scheduled_date, :scheduled_time, :state)
  end

  def find_call_log
    unless params[:cid].present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end

    @call_log = CallLog.find params[:cid]
    unless @call_log.present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end
  end
  
  def find_appointment
    @appointment = @call_log.appointments.find params[:id]
    unless @appointment.present?
      flash[:alert] = "Appointment not found"
      redirect_back fallback_location: users_call_logs_path
    end
  end
end

app/controllers/users/billings_controller.rb
class Users::BillingsController < UsersController
  def index
    respond_to do |format|
      format.html {
        @billing_grid = initialize_grid(Bill,
                                        name: 'bill',
                                        enable_export_to_csv: true)
        export_grid_if_requested('bill' => 'bill_grid')
      }
    end
  end
end

app/controllers/users/branches_controller.rb
module Users
  class BranchesController < UsersController
    before_action :find_branch, only: [:edit, :update, :destroy]

    def index
      @branches = Branch.all
    end

    def new
      @branch = Branch.new
    end

    def create
      @branch = Branch.new(branch_params)
      if @branch.save
        flash[:success] = 'Branch successfully created.'
        redirect_to users_branches_path
      else
        flash[:error] = 'Something went wrong'
        render 'new'
      end
    end

    def edit
    end

    def update
      if @branch.update_attributes(branch_params)
        flash[:success] = 'Branch was successfully updated'
        redirect_to users_branches_path
      else
        flash[:error] = 'Something went wrong'
        render 'edit'
      end
    end

    def destroy
      if @object.destroy
        flash[:success] = 'Branch was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end

      redirect_to users_branches_path
    end


    private

    def branch_params
      params.require(:branch).permit(:name, :code, :telephone, :location)
    end

    def find_branch
      @branch = Branch.find(params[:id])
      unless @branch.present?
        flash[:error] = 'Branch not found.'
        redirect_to users_branches_path
      end
    end
  end
end

app/controllers/users/call_logs_controller.rb
module Users
  class CallLogsController < UsersController
    before_action :find_call_log, except: [:index, :new, :create]

    def index
      respond_to do |format|
        format.html {
          @filterrific = initialize_filterrific(
            record_scope.page(params[:page]),
            params[:filterrific],
            persistence_id: false
          ) || return

          @call_logs_grid = initialize_grid(@filterrific.find.page(params[:page]),
                                            name: 'call_log',
                                            include:  [:customer, :user, :comments],
                                            order:  'call_logs.created_at',
                                            order_direction: 'desc')
          export_grid_if_requested('call_log' => 'call_log_grid')
        }
  
        format.json {
        }
      end
    end

    def new
      @call_log = current_user.call_logs.new
      @call_log.build_customer
    end

    def create
      @log = current_user.call_logs.new(log_params)
      if @log.save
        flash[:success] = "Call Log successfully created."
        redirect_to users_call_log_path(@log)
      else
        flash[:error] = "Something went wrong while creating call log."
        render 'new'
      end
    end

    def edit
    end

    def update
      if @call_log.update_attributes(log_params)
        flash[:success] = "Call Log was successfully updated"
        redirect_to users_call_log_path(@call_log)
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
    end

    def destroy
      if @call_log.destroy
        flash[:success] = 'Call Log was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end

      redirect_to users_call_logs_path
    end

    def transition
      begin
        if @call_log.update_attribute(:state, log_params[:state])
          flash[:success] = "Call Log is now #{@call_log.state.humanize}."
        else
          flash[:error] = "Error changing status"
        end
      rescue => exception
        flash[:error] = "Sorry, you are unallowed to '#{log_params[:state]}' property. "
      end

      redirect_to users_call_log_path(@call_log)
    end

    private

    def log_params
      params.require(:call_log).permit(:budget_currency, :budget_amount, :status,
                                  :property_locations, :property_names,
                                  customer_attributes: [:first_name, :last_name, :telephone])
    end

    def record_scope
      if can?("view_all", "call_logs")
        CallLog.includes(:user).where(deleted_at: nil).order(created_at: :desc)
      else
        current_user.call_logs.includes(:user).where(deleted_at: nil).order(created_at: :desc)
      end
    end

    def find_call_log
      @call_log = record_scope.find(params[:id])
      unless @call_log.present?
        flash[:error] = "Call Log not found"
        redirect_to users_call_logs_path
      end
    end
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < UsersController
  before_action :find_call_log
  before_action :find_comment, except: [:new, :create]

  def new
    @comment = @call_log.comments.new
    @comment.user_id = current_user.id
  end

  def create
    @comment = @call_log.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      @call_log.update_attribute(:status, @comment.state)
      flash[:success] = "Comment successfully created"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(comment_params)
      @call_log.update_attribute(:status, @call_log.comments.last&.state || @call_log.status)
      flash[:success] = "Comment was successfully updated"
      redirect_to users_call_log_path(@call_log)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @comment.destroy
      @call_log.update_attribute(:status, @call_log.comments.last&.state || "Response pending")
      flash[:success] = 'Comment was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end

    redirect_to users_call_log_path(@call_log)
  end


  private
  def comment_params
    params.require(:comment).permit(:details, :state)
  end

  def find_call_log
    unless params[:cid].present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end

    @call_log = CallLog.find params[:cid]
    unless @call_log.present?
      flash[:alert] = "Call log not found"
      redirect_back fallback_location: users_call_logs_path
      return ;
    end
  end

  def find_comment
    @comment = @call_log.comments.find params[:id]
    unless @comment.present?
      flash[:alert] = "comment not found"
      redirect_back fallback_location: users_call_logs_path
    end
  end
end

app/controllers/users/customers_controller.rb
class Users::CustomersController < UsersController
  def index
    respond_to do |format|
      format.html { 
        @q = Customer.ransack(params[:q])
        @customers = @q.result(distinct: true).page params[:page]
       }

      format.json {
      }
    end
  end
end

app/controllers/users/filters_controller.rb
class Users::FiltersController < UsersController
  # params - type
  # 1. property
  def index
    results = 
      case params[:type]
      when 'property'
        Property.new.as_json.keys.sort
      else
        Property.new.as_json.keys.sort
      end

    render json: results, status: :ok
  end

  def options
    unless params[:field].present?
      render json: [], status: :ok
      return ;
    end

    results = 
      case params[:type]
      when 'property'
        Property.select(:"#{params[:field]}").all.pluck(:"#{params[:field]}").uniq.compact.sort
      end

    render json: results, status: :ok
  end
end

app/controllers/users/geocodes_controller.rb
module Users
  class GeocodesController < UsersController
    def location
      results = Geocoder.search([params[:lat], params[:lng]])
      result = results.first
      address = result.data['address']
      render json: {address: result.address,
                    city: address['city'],
                    state: address['state'],
                    suburb: address['suburb'],
                    road: address['road'],
                    postcode: address['postcode']}, status: :ok
    end
  end
end

app/controllers/users/help_controller.rb
class Users::HelpController < UsersController
end

app/controllers/users/lands_controller.rb
class Users::LandsController < UsersController
  before_action :find_land, only: [:edit, :update, :destroy]

  def index
  end

  def new
  end

  def edit
  end

  def update
    if @land.update_attributes(land_params)
      flash[:success] = "Land details was successfully updated"
      redirect_to users_land_path(@land)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def transition
    begin
      if @land.send("#{land_params[:state]}!")
        flash[:success] = "Land is now #{@land.state}."
      else
        flash[:error] = "Error uploading image."
      end
    rescue => exception
      flash[:error] = "Sorry, you are unallowed to '#{land_params[:state]}' property. "
    else
    end

    redirect_to users_land_path(@land)
  end

  private

  def land_params
    params.require(:land).permit(:amount, :currency, :customer_id, :state)
  end

  def find_land
    @land = record_scope.find(params[:id])
    unless @land.present?
      flash[:error] = "Land details not found"
      redirect_to users_lands_path
    end
  end

  def record_scope
    if can?("view_all", "lands")
      Land.where(deleted_at: nil).order(created_at: :desc)
    else
      current_user.lands.order(created_at: :desc)
    end
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < UsersController
  before_action :find_property

  def index
    @images = @property.images.map(&:service_url)
    render json: {images: @images}, status: :ok
  end

  private
  def find_property
    @property = current_user.properties.find_by_id(params[:property_id])
    unless @property.present?
      render json: {error: 'Property not found'}, status: :failed
      return ;
    end
  end
end

app/controllers/users/profiles_controller.rb
module Users
  class ProfilesController < UsersController
    before_action :find_user, except: %i[index new create]

    def index
      @users = User.all.order(:created_at)
    end

    def new
      @user = User.new
      @user.roles.build
    end

    # Create a new user
    def create
      @user = User.invite!(user_params, current_user)
      # Todo: Check option autoconfirm
      @user.confirm
      # Todo: check option for auto invitation accept
      User.accept_invitation!(invitation_token: @user.raw_invitation_token, password: user_params[:password])

      redirect_to users_profiles_path
    end

    def edit
    end

    def update
      if @user.update_attributes(user_params)
        flash[:success] = "User details was successfully updated"
        redirect_to users_profiles_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
    end

    def roles
    end

    def update_roles
    end

    private

    def user_params
      params.require(:user).permit(:first_name,
                                  :last_name,
                                  :email,
                                  :password,
                                  :password_confirmation, role_ids: [])
    end

    def find_user
      @user = User.find params[:id]
      unless @user.present?
        flash[:error] = 'User not found.'
        redirect_to users_profiles_path
        return ;
      end
    end
  end
end

app/controllers/users/settings_controller.rb
module Users
  class SettingsController < UsersController
    def index
    
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  private
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path(subdomain: current_account.subdomain_name)
    end
  end
end

app/helpers/users/appointments_helper.rb
module Users::AppointmentsHelper
end

app/helpers/users/billings_helper.rb
module Users::BillingsHelper
end

app/views/users/properties/_form.html.slim
= simple_form_for(@property, defaults: { wrapper: false }, as: :property, method: action, url: url, html: { multipart: true }) do |f|
  p PROPERTY IMAGES
  .form-group.no-margin-bottom
    = f.file_field :images, multiple: true, class: 'form-control', required: true
  .progress-wrapper
    .progress
      .progress-bar role="progressbar" 0%
  br
  br
  .form-group
    = f.input :code, label: "Code (Autogenerated)", input_html: {class: 'form-control', readonly: true}
  .row
    .form-group.col-md-6
      = f.input :offer_type, label: "Offer type", collection: Property::OFFER_TYPE, required: true, input_html: {class: 'form-control'}
    .form-group.col-md-6
      = f.input :category, label: "Category", collection: Property::CATEGORY, input_html: {class: 'form-control'}, required: true
  .row
    .form-group.col-md-6
      = f.input :build_type, label: "Type of Building", collection: Property::BUILDING_TYPE.sort, input_html: {class: 'form-control'}, required: true
    .form-group.col-md-6
      = f.input :name, label: "Property Name", input_html: {class: 'form-control', list: 'names'}
      datalist#names
        - Property::PROPERTY_NAME.sort.each do |property_name|
          option value='#{property_name}'
  .row
    .form-group.col-md-2
      = f.input :currency, label: "Currency", collection: Property::CURRENCIES, input_html: {class: 'form-control'}
    .form-group.col-md-10
      = f.input :price, label: "Price", input_html: {class: 'form-control'}, required: true
  .form-group
    = f.input :tenure, label: "Tenure", collection: Property::TENURE.sort, input_html: {class: 'form-control'}
  br
  p LOCATION DETAILS
  .row
    .form-group.col-md-4
      = f.input :location_latlng, label: "Location (GPS)", input_html: {class: 'form-control', readonly: true}
      button.btn.btn-primary.generate_gps type="button" Generate
    .form-group.col-md-4
      = f.input :location_city, label: "City", input_html: {class: 'form-control'}
    .form-group.col-md-4
      = f.input :location_state, label: "State / Region", input_html: {class: 'form-control'}
  .row
    .form-group.col-md-4
      = f.input :location_suburb, label: "Suburb", input_html: {class: 'form-control'}
    .form-group.col-md-4
      = f.input :location_road, label: "Road", input_html: {class: 'form-control'}
    .form-group.col-md-4
      = f.input :location_postcode, label: "Postcode", input_html: {class: 'form-control'}
  .form-group
    = f.input :location, as: :text, label: "Full Location (Autogenerated)", input_html: {class: 'form-control', placeholder: 'e.g. City, Country'}
  .form-group
    = f.input :landmark, as: :string, label: "Landmark", input_html: {class: 'form-control location'}
  br
  br
  p OTHER DETAILS
  .form-group.col-md-4
    = f.input :meter, label: "Type of Meter", collection: Property::METER.sort, input_html: {class: 'form-control', placeholder: 'e.g. City, Country'}
  .row
    .form-group.col-md-4
      = f.input :no_of_tenant, label: "Number of Tenants on property", input_html: {class: 'form-control'}
    .form-group.col-md-4
      = f.input :bedrooms, label: "Number of Bedrooms", input_html: {class: 'form-control'}
    .form-group.col-md-4
      = f.input :bathrooms, label: "Number of Bathrooms", input_html: {class: 'form-control'}
  .row
    .form-group.col-md-8
      = f.input :size, label: "Size", input_html: {class: 'form-control'}
    .form-group.col-md-4
      = f.input :size_unit, label: "Unit", collection: Property::SIZE_UNIT, input_html: {class: 'form-control'}
  .form-group
    = f.input :features, label: "Property features", as: :check_boxes, collection: Property::FEATURES.sort
  .form-group
    = f.input :water_source, label: "Water source", collection: Property::WATER_SOURCE.sort, as: :check_boxes
  .form-group
    = f.input :utilities, as: :check_boxes, label: "Utilities", collection: Property::UTILITIES.sort
  .form-group
    = f.input :other_info, as: :text, label: "Other information", input_html: {class: 'form-control', rows: 5}

  br
  br
  p OWNER'S INFORMATION
  = f.simple_fields_for :owner do |o|
    .form-group
      = o.input :name, label: 'Full Name', input_html: {class: 'form-control'}
    .form-group
      = o.input :telephone, label: 'Telephone', input_html: {class: 'form-control'}
    .form-group
      = o.input :location, as: :string, label: 'Location', input_html: {class: 'form-control location'}
  .form-group
    = f.input :has_caretaker, label: 'Property owner is different from the caretaker.', input_html: {class: 'toggler'}

  br
  #property_has_caretaker.toggle-div style="#{@property.has_caretaker ? 'display: visible' : 'display: none'}"
    p CARETAKER'S INFORMATION
    = f.simple_fields_for :caretaker do |o|
      .form-group
        = o.input :name, label: 'Full Name', input_html: {class: 'form-control'}
      .form-group
        = o.input :telephone, label: 'Telephone', input_html: {class: 'form-control'}
      .form-group
        = o.input :location, as: :string, label: 'Location', input_html: {class: 'form-control location'}
  .row
    .col-md-3
      = f.button :submit, 'SAVE PROPERTY', class: 'btn-success'
    .col-md-5
    .col-m-4
      - if current_page?(new_users_property_path)
        = f.button :submit, 'Temporarily Save Property', class: 'btn-warning'

/ javascript:
/   $(document).ready(function(){
/     var multiple_photos_form = $('#new_property');
/     multiple_photos_form.fileupload({
/       dataType: 'script',
/       add: function (e, data) {
/         types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
/         file = data.files[0];
/         if (types.test(file.type) || types.test(file.name)) {
/           data.submit();
/         }
/         else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
/       }
/     });

/     multiple_photos_form.on('fileuploadsubmit', function (e, data) {
/       data.formData = {'photo[author]': $('#photo_author').val()};
/     });

/     var wrapper = multiple_photos_form.find('.progress-wrapper');
/     var progress_bar = wrapper.find('.progress-bar');

/     multiple_photos_form.on('fileuploadstart', function() {
/       var progress = parseInt(0, 10);
/       wrapper.show();
/       progress_bar.css('width', progress + '%').text(progress + '%');
/     });

/     multiple_photos_form.on('fileuploaddone', function() {
/       wrapper.hide();
/       progress_bar.width(0); // Revert progress bar's width back to 0 for future uploads
/     });

/     multiple_photos_form.on('fileuploadprogressall', function (e, data) {
/       var progress = parseInt(data.loaded / data.total * 100, 10);
/       progress_bar.css('width', progress + '%').text(progress + '%');
/     });
/   })

app/views/users/properties/_property_grid.html.erb
<%= grid(@properties_grid, show_filters: false) do |g|
  g.column name: 'DATE/TIME', attribute: 'created_at' do |property|
    property.created_at.strftime("%a, %d %b %Y %H:%M:%S")
  end

  g.column name: 'CODE', attribute: 'code' do |property|
    property.code
  end

  g.column name: 'OFFER TYPE', attribute: 'offer_type', custom_filter: Property::OFFER_TYPE do |property|
    property.offer_type.titleize
  end

  g.column name: 'NAME', attribute: 'name', custom_filter: Property::PROPERTY_NAME do |property|
    property.name
  end

  g.column name: 'SUBURB', attribute: 'location_suburb', custom_filter: :auto do |property|
    property.location_suburb
  end

  g.column name: 'CURRENCY', attribute: 'currency', custom_filter: Property::CURRENCIES do |property|
    property.currency
  end

  g.column name: 'PRICE', attribute: 'price' do |property|
    property.price
  end

  g.column name: 'TENURE', attribute: 'tenure', custom_filter: Property::TENURE do |property|
    property.tenure
  end

  g.column name: 'STATE', attribute: 'state', custom_filter: :auto do |property|
    property.state.titleize
  end

  if can?("view", "properties")
    g.column do |property|
      link_to('View', users_property_path(property))
    end
  end

  if can?("edit", "properties")
    g.column do |property|
      link_to('Edit', edit_users_property_path(property))
    end
  end

  if can?("delete", "properties")
    g.column do |property|
      link_to('Delete', users_property_path(property), method: 'DELETE', data: {confirm: 'Do you want to delete?'})
    end
  end
end -%>

app/views/users/properties/edit.html.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 Properties
          p.mb-md-0 Edit property details.
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor &nbsp;Properties&nbsp;/&nbsp;
          p.text-primary.mb-0.hover-cursor Edit

a.btn.btn-danger href="#{users_properties_path}" < Back
br
br
.col-md-8.grid-margin.stretch-card
  .card
    .card-body
      h4.card-title Edit Property
      = render partial: "form", locals: {action: :put, url: users_property_path(@property)}

app/views/users/properties/new.html.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 Properties
          p.mb-md-0 Add a new property.
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor &nbsp;Properties&nbsp;/&nbsp;
          p.text-primary.mb-0.hover-cursor New

.col-md-8.grid-margin.stretch-card
  .card
    .card-body
      h4.card-title Add New Property
      = render partial: "form", locals: {action: :post, url: users_properties_path}

app/views/users/properties/new_rent.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 New Rent
          p.mb-md-0 Enter details to rent out property.
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor &nbsp;Properties&nbsp;/&nbsp;
          p.text-primary.mb-0.hover-cursor New Rent

a.btn.btn-danger href="#{users_property_path(@property)}" < Back
br
br
.col-8.grid-margin.stretch-card
  .card
    .card-body
      h4.card-title Rent out Property
      = simple_form_for(@payment, as: :payment, method: :post, url: payment_users_property_path(@property), html: { multipart: true }) do |f|
        .row
          .form-group.col-md-3
            = f.input :currency, label: "Currency", collection: Property::CURRENCIES, input_html: {class: 'form-control'}
          .form-group.col-md-9
            = f.input :amount, label: "Amount", input_html: {class: 'form-control'}
        .row
          .form-group.col-md-6
            = f.association :customer, label: "Customer", input_html: {class: 'form-control'}
          .form-group.col-md-6
            = f.association :seller, label: "Sold by", input_html: {class: 'form-control'}
        .form-group
          = f.input :date_sold, label: "Date sold"
        .row
          .form-group.col-md-6
            = f.input :rent_from, label: "Rent From"
          .form-group.col-md-6
            = f.input :rent_to, label: "Rent To"
        .form-group
          = f.input :other_details, label: "Other information", input_html: {class: 'form-control'}
          = f.input :transaction_type, as: :hidden
        .form-group
          = f.button :submit, "SAVE PAYMENT", class: 'btn btn-success'
        

app/views/users/properties/new_sale.slim
.row
  .col-md-12.grid-margin
    .d-flex.justify-content-between.flex-wrap
      .d-flex.align-items-end.flex-wrap
        .mr-md-3.mr-xl-5
          h2 New Sale
          p.mb-md-0 Enter details to sell property.
        .d-flex
          i.mdi.mdi-home.text-muted.hover-cursor
          p.text-muted.mb-0.hover-cursor &nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;
          p.text-muted.mb-0.hover-cursor &nbsp;Properties&nbsp;/&nbsp;
          p.text-primary.mb-0.hover-cursor New Sale

a.btn.btn-danger href="#{users_property_path(@property)}" < Back
br
br
.col-8.grid-margin.stretch-card
  .card
    .card-body
      h4.card-title Sell Property
      = simple_form_for(@payment, as: :payment, method: :post, url: payment_users_property_path(@property), html: { multipart: true }) do |f|
        .row
          .form-group.col-md-3
            = f.input :currency, label: "Currency", collection: Property::CURRENCIES, input_html: {class: 'form-control'}
          .form-group.col-md-9
            = f.input :amount, label: "Amount", input_html: {class: 'form-control'}
        .row
          .form-group.col-md-6
            = f.association :customer, label: "Customer", input_html: {class: 'form-control'}
          .form-group.col-md-6
            = f.association :seller, label: "Sold by", input_html: {class: 'form-control'}
        .form-group
          = f.input :date_sold, label: "Date sold"
        .form-group
          = f.input :other_details, label: "Other information", input_html: {class: 'form-control'}
          = f.input :transaction_type, as: :hidden
        .form-group
          = f.button :submit, "SAVE PAYMENT", class: 'btn btn-success'
        