config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  mount Maily::Engine, at: '/maily'
  get 'accounts/new'

  # Action cable
  mount ActionCable.server => '/cable'

  constraints(SubdomainPresent) do
    root 'users#index', as: :subdomain_root

    # users - routes
    devise_for :users, path: ''
    resources :users, path: '', only: :index
    namespace :users, path: '' do
      resources :appointments
      resources :branches
      resources :comments
      resources :profiles do
        member do
          get :roles
          patch :update_roles
        end
      end
      resources :roles do
        member do
          get :permissions
          patch :update_permissions
        end
      end
      resources :settings
      resources :help, only: :index
      resources :customers
      resources :call_logs do
        member do
          post  :create_comment
          patch :transition
        end
      end
      resources :lands
      resources :properties do
        member do
          patch :upload_pic
          get   :remove_pic
          patch :transition
          get   :new_rent
          get   :new_sale
          post  :payment
          patch :download_pics
        end
      end
      resources :geocodes do
        collection do
          get :location
        end
      end
      resources :filters do
        collection do
          get :options
        end
      end
    end
  end  

  constraints(SubdomainBlank) do 
    root 'home#index'
    resources :accounts, only: [:index, :new, :create] do
      collection do
        get :forgot
        post :remember
        post :find_team
      end
    end

    # admins - routes
    resources :admins, only: :index
    devise_for :admins
  end

  # IP blacklisting for admin website
end

app/models/account.rb
class Account < ApplicationRecord
  RESTRICTED_SUBDOMAIN = %w(www)
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  validates :owner, presence: true
  accepts_nested_attributes_for :owner, allow_destroy: true

  validates :subdomain_name, presence: true,
                          uniqueness: { case_sensitive: false},
                          format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                          exclusion: {in: RESTRICTED_SUBDOMAIN, message: 'restricted'}

  before_validation :downcase_account

  private
  def downcase_account
      self.subdomain_name = subdomain_name.try(:downcase) 
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def index
  end
  
  def forgot
  end

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(accounts_params)
    @account.subdomain_name = get_subdomain(@account.name)
    if @account.valid?
      Apartment::Tenant.create(@account.subdomain_name)
      Apartment::Tenant.switch!(@account.subdomain_name)
      if @account.save
        redirect_to new_user_session_url(subdomain: @account.subdomain_name)
      else
        render action: 'new'
      end
    else
      render action: 'new'
    end
  end

  def find_team
    team_name = get_subdomain(params[:team_name])
    if team_name.present? && !team_name.nil? && !team_name.blank?
      Apartment::Tenant.switch!('public')
      if search_team(team_name)
        begin
          Apartment::Tenant.switch!(team_name)
          redirect_to new_user_session_url(subdomain: team_name)
        rescue => exception
          flash[:alert] = "Team Not Found."
          redirect_to accounts_path
        end
      else
        flash[:alert] = "Team Not Found."
        redirect_to accounts_path
      end
    else
      flash[:alert] = "Please Enter the Team Name."
      redirect_to accounts_path
    end
  end

  def remember
  end

  protected
  def search_team(team_name)
    @account ||= Account.find_by(subdomain_name: team_name)
  end

  private
  def accounts_params
    params.require(:account).permit(:name, owner_attributes: [:first_name, :last_name, :is_admin, :email, :password, :password_confirmation])
  end 

  def get_subdomain(str)
    str.strip.downcase.gsub(" ", "-")
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/forgot.slim
.content-wrapper.d-flex.align-items-stretch.auth.auth-img-bg
  .row.flex-grow
    .col-lg-6.d-flex.align-items-center.justify-content-center
      .auth-form-transparent.text-left.p-3
        .brand-logo
          = image_tag("logo/logo.png")
        h4 Forgot team?
        = render 'components/messages'
        = form_tag(accounts_path, class: 'pt-3') do |f| 
          .form-group
            label for="e" Your Email
            = text_field nil, :email, autofocus: true, class: 'form-control form-control-lg', placeholder: "user@example.com"
          .my-3
            = submit_tag "REMEMBER TEAM NAMES", class: 'btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn'
          .form-group
            .input-group
              = link_to  "Already have a team? Find team", accounts_path, class: 'auth-link text-black'
          .form-group
            .input-group
              = link_to  "Create a new workspace for your team", new_account_path, class: 'auth-link text-black'
    .col-lg-6.team-half-bg.d-flex.flex-row
      p.text-white.font-weight-medium.text-center.flex-grow.align-self-end Copyright &copy; 2018  All rights reserved.

app/views/accounts/index.slim
.content-wrapper.d-flex.align-items-stretch.auth.auth-img-bg
  .row.flex-grow
    .col-lg-6.d-flex.align-items-center.justify-content-center
      .auth-form-transparent.text-left.p-3
        .brand-logo
          = image_tag("logo/logo.png")
        h4 Welcome back!
        = render 'components/messages'
        = form_tag(find_team_accounts_path, class: 'pt-3') do |f| 
          .form-group
            label for="e"  Company / Workspace Name
            = text_field nil, :team_name, autofocus: true, class: 'form-control form-control-lg', placeholder: "ABC Company"
          .my-3
            = submit_tag "FIND TEAM", class: 'btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn'
          .form-group
            .input-group
              = link_to  "Create a new workspace for your team", new_account_path, class: 'auth-link text-black'
          .form-group
            .input-group
              = link_to  "I don't remember team's name?", forgot_accounts_path, class: 'auth-link text-black'
    .col-lg-6.login-half-bg.d-flex.flex-row
      p.text-white.font-weight-medium.text-center.flex-grow.align-self-end Copyright &copy; 2018  All rights reserved.

app/views/accounts/new.slim
.content-wrapper.d-flex.align-items-stretch.auth.auth-img-bg
  .row.flex-grow
    .col-lg-6.d-flex.align-items-center.justify-content-center
      .auth-form-transparent.text-left.p-3
        .brand-logo
          = image_tag("logo/logo.png")
        h4 Welcome back!
        = render 'components/messages'
        = form_for(@account, class: 'pt-3') do |f| 
          .form-group
            label for="e"  Company / Workspace Name
            = f.text_field :name, autofocus: true, class: 'form-control form-control-lg', placeholder: "ABC Company"
          = f.fields_for :owner do |o|
            .form-group
              label for="first_name"  First Name
              = o.text_field :first_name, autofocus: true, class: 'form-control form-control-lg'
            .form-group
              label for="last_name"  Last Name
              = o.text_field :last_name, autofocus: true, class: 'form-control form-control-lg'
            .form-group
              label for="email"  Email
              = o.email_field :email, autofocus: true, class: 'form-control form-control-lg', placeholder: "user@email.com"
            .form-group
              label for="password"  Password
              = o.password_field :password, autofocus: true, class: 'form-control form-control-lg'
            .form-group
              label for="email"  Confirm Password
              = o.password_field :password_confirmation, autofocus: true, class: 'form-control form-control-lg'
          .my-3
            = f.submit "CREATE TEAM", class: 'btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn'
          .form-group
            .input-group
              = link_to  "Already have a team? Find team", accounts_path, class: 'auth-link text-black'
          .form-group
            .input-group
              = link_to  "I don't remember team's name?", forgot_accounts_path, class: 'auth-link text-black'
    .col-lg-6.team-half-bg.d-flex.flex-row
      p.text-white.font-weight-medium.text-center.flex-grow.align-self-end Copyright &copy; 2018  All rights reserved.